### ISSUE TITLE
VROID VRM -> GLTF -> bone no root issue

### ISSUE THREAD

**Issue by enzyme69** [julienduroure/gltf2-blender-importer#19]
I am testing this GLTF for character made in VROID (Japanese) app.

Somewhat I keep getting error from below:

```
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/io_scene_gltf2_importer/__init__.py", line 51, in execute
    return self.import_gltf2(context)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/io_scene_gltf2_importer/__init__.py", line 57, in import_gltf2
    success, txt = self.gltf.read()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/io_scene_gltf2_importer/io/__init__.py", line 176, in read
    self.scene.read()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/io_scene_gltf2_importer/scene/__init__.py", line 51, in read
    if skin.root != skin.bones[0]:
AttributeError: 'Skin' object has no attribute 'root'

location: <unknown location>:-1


```

I tried alternative:
https://github.com/ksons/gltf-blender-importer

Above works for all the meshes, but the bones become "Empty".

Wondering if there is solution using this version of GLTF 2 importer?

**Comment by julienduroure** [comment]
Hello,
Thanks for your report.
Can you please upload (or give me a link) to a glTF2.0 file created with this app?

**Comment by julienduroure** [comment]
I may have found the error, committed a potential fix, but I really need an example glTF file from VROID to test it correctly

**Comment by enzyme69** [comment]
@julienduroure I just saw this after you mentioned at Twitter. Will test again thanks!

VROID file attached, cheers~ (I renamed the extension to GLTF, but not sure if they are exactly the same...)

[VRoidTwo.gltf.zip](https://github.com/julienduroure/gltf2-blender-importer/files/2293274/VRoidTwo.gltf.zip)

**Comment by julienduroure** [comment]
Import is now fixed.
Still have a global bone issue, will be followed in #20
